apiVersion: v1
kind: Deployment
metadata:
  name: testcicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcicd
  template:
    metadata:
      labels:
        app: testcicd
    spec:
      containers:
        - name: testcicd
          image: gcr.io/test-375418/oncom06/testcicd:latest
          ports:
            - containerPort: 3000
