apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcicd
  template:
    metadata:
      labels:
        app: testcicd
    spec:
      containers:
        - name: oncom06/testcicd
          image: testcicd:latest
          ports:
            - containerPort: 3000
