apiVersion: v1
kind: Deployment
metadata:
  name: testcicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testcicd
  template:
    metadata:
      labels:
        app: testcicd
    spec:
      containers:
        - name: testcicd
          image: asia-southeast2-docker.pkg.dev/$GOOGLE_PROJECT/testcicd:latest
          ports:
            - containerPort: 3000
