apiVersion: apps/v1
kind: Deployment
metadata:
  name: testcicd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: testcicd
          image: gcr.io/$GOOGLE_PROJECT/testcicd:latest
          ports:
            - containerPort: 3000
