apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  #type: LoadBalancer  # or NodePort, ClusterIP, etc.
