apiVersion: v1
kind: Service
metadata:
  name: testcicd
spec:
  selector:
    app: testcicd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # or NodePort, ClusterIP, etc.
